<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="height" value="0.01"/>
  <xacro:property name="width" value="0.1"/>
  <xacro:property name="length" value="${height/width}"/>

  <material name="yellow">
    <color rgba="1 1 0 1"/>
  </material>

  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>

  <material name="green">
    <color rgba="0 1 0 1"/>
  </material>

  <material name="blue">
    <color rgba="0 0 1 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <xacro:macro name="create_link" params="name mass material_name">
    <link name="${name}_link">
      <visual>
        <geometry>
              <mesh filename="package://rasbot_description/meshes/chassis.stl"/>
          </geometry>
          <material name="${material_name}"/>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://rasbot_description/meshes/chassis.stl"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${mass}"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.02" iyy="0.05" izz="0.06" ixy="0" ixz="0" iyz="0"/>
        </inertial>
    </link>
  </xacro:macro>

  <xacro:create_link name="base" mass="2.0" material_name="blue"/>

  <link name="link1">
    <visual>
      <geometry>
        <box size="${height} ${width} ${length}"/>
      </geometry>
    </visual>
    <collision>
        <geometry>
            <box size="${height} ${width} ${length}"/>
        </geometry>
    </collision>
  </link>
  
  <joint name="joint1" type="fixed">
    <origin xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="link1"/>
  </joint>
</robot>